export const TITLE_SCREEN_BALL_SPEED = 0.03
export const GAME_BALL_SPEED = 0.07
export const FONT_SIZE_TITLE_TO_HEIGHT_RATIO = 0.15
export const FONT_SIZE_SUBTITLE_TO_HEIGHT_RATIO = 0.03

export const BALL_RADIUS_PERCENT = 0.015

export const PADDLE_WIDTH_PERCENT = 0.018
export const PADDLE_HEIGHT_PERCENT = 0.25
export const PADDLE_DISTANCE_FROM_SIDE_PERCENT = 0.1
export const OPPONENT_IDLE_INCORRECTNESS = 0.8